WebAPIWithCoreMvc/Areas/Admin/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Reflection.Metadata;
using System.Security.Claims;
using System.Threading.Tasks;
using Core.Utilities.Messages;
using Entities.Abstract.Enums;
using Entities.Dtos.Auths;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebAPIWithCoreMvc.ApiServices.Interfaces;

namespace WebAPIWithCoreMvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthController : Controller
    {
        private IAuthApiService _authApiService;
        private IHttpContextAccessor _httpContextAccessor;

        public AuthController(IAuthApiService authApiService, IHttpContextAccessor httpContextAccessor)
        {
            _authApiService = authApiService;
            _httpContextAccessor = httpContextAccessor;
        }

        [HttpGet]
        public IActionResult Login()
        {
            GetLanguages();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginDto loginDto)
        {
            GetLanguages();

            string _language = loginDto.LanguageId == (int)EnumLanguages.Turkish ? Constants.LangTR : Constants.LangEN;

            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(_language)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddDays(7) }
            );


            var user = await _authApiService.LoginAsync(loginDto);
            if (user != null && !user.Success)
            {
                ModelState.AddModelError("", "Kullanıcı adı veya şifre hatalı!");
                 return View(loginDto);
            }
            var userClaims = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            userClaims.AddClaim(new Claim("token", user.Data.Token));
            userClaims.AddClaim(new Claim("language", _language));
            userClaims.AddClaim(new Claim(ClaimTypes.NameIdentifier, user.Data.AppUserID.ToString()));
            userClaims.AddClaim(new Claim(ClaimTypes.Name, user.Data.UserName));
            userClaims.AddClaim(new Claim("FullName", user.Data.FullName));
            var claimPrincipal = new ClaimsPrincipal(userClaims);
            var authProperties = new AuthenticationProperties() { IsPersistent = loginDto.IsRememberMe };
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimPrincipal, authProperties);
            return RedirectToAction(Constants.List, Constants.AppUser, new { area = Constants.Admin });
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(Constants.Login);
        }

        private void GetLanguages()
        {
            List<SelectListItem> languageList = new()
            {
                new SelectListItem { Value = "1", Text = "Türkçe" },
                new SelectListItem { Value = "2", Text = "English" },
            };
            ViewBag.LanguageList = languageList;
        }
    }
}

WebAPIWithCoreMvc/Areas/Admin/ViewComponents/LeftMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using WebAPIWithCoreMvc.ApiServices.Interfaces;
using WebAPIWithCoreMvc.Models;

namespace WebAPIWithCoreMvc.Areas.Admin.ViewComponents
{
    public class LeftMenuViewComponent : ViewComponent
    {
        private readonly IPageApiService _pageApiService;
        public LeftMenuViewComponent(IPageApiService pageApiService)
        {
            _pageApiService = pageApiService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            LeftMenuViewModel viewModel = new LeftMenuViewModel();
            var result = await _pageApiService.GetListAdminPanelLeftMenuAsync();
            viewModel.MainPage = result.Data.Where(x => x.ParentID == null ).ToList();
            viewModel.ParentPage = result.Data.Where(x => x.ParentID != null ).ToList();
            return View(viewModel);
        }

    }
}

WebAPIWithCoreMvc/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
@using Core.Utilities.Messages
@inject Core.Utilities.Localization.ILocalizationService _localizationService

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>E-Ticaret 2021</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0-rc/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0-rc/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0-rc/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0-rc/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0-rc/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0-rc/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0-rc/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/lib/AdminLTE-3.2.0-rc/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="~/lib/AdminLTE-3.2.0-rc/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
        </div>

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                @*   <li class="nav-item d-none d-sm-inline-block">
                <a href="index3.html" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">Contact</a>
                </li>*@
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Navbar Search -->
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Auth" asp-action="Logout" role="button">
                        <i class="fas fa-sign-out-alt" title="Oturumu Kapat">&nbsp;@_localizationService[ResultCodes.BUTTON_SignOut]</i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Sidebar Menu -->
        @await Component.InvokeAsync("LeftMenu")
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">Dashboard</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">Dashboard v1</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            @RenderBody()
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.2.0-rc
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/lib/AdminLTE-3.2.0-rc/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/lib/AdminLTE-3.2.0-rc/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/lib/AdminLTE-3.2.0-rc/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/lib/AdminLTE-3.2.0-rc/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/lib/AdminLTE-3.2.0-rc/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/lib/AdminLTE-3.2.0-rc/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/lib/AdminLTE-3.2.0-rc/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/lib/AdminLTE-3.2.0-rc/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/lib/AdminLTE-3.2.0-rc/plugins/moment/moment.min.js"></script>
    <script src="~/lib/AdminLTE-3.2.0-rc/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/lib/AdminLTE-3.2.0-rc/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/lib/AdminLTE-3.2.0-rc/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/lib/AdminLTE-3.2.0-rc/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/lib/AdminLTE-3.2.0-rc/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    @*<script src="~/lib/AdminLTE-3.2.0-rc/dist/js/demo.js"></script>*@
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/lib/AdminLTE-3.2.0-rc/dist/js/pages/dashboard.js"></script>
</body>
</html>